services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: api_container
    build:
      context: ./api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENSEARCH_NODE=${OPENSEARCH_NODE}
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  job:
    container_name: job_container
    build:
      context: ./job
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENSEARCH_NODE=${OPENSEARCH_NODE}
    depends_on:
      - mysql

volumes:
  mysql-data:
